
var constants = module.exports = {
    DIR:{
    	MATCH: 'Match the definitions with their words.',
    	COPY: 'Type the whole statement into the textbox. Do not worry about spacing.',
    	STUDY: 'Study the information for future Quarter Quizzes.',
    	ANSWERQ: 'Answer the question with the single correct answer.',
    	PICTURE: 'Use the image to answer the question.',
    	ANGLE: 'Use the angles given to classify the type of triangle.',
    	PROPERTY: 'Choose an example of each property.',
    	FILL: 'Fill in the blanks to answer the questions.',
        FREE: 'Hit submit and prepare for the next quiz',
    	CLICK_PRIME: 'Click all the prime numbers under 100.',
    	LIST_PRIME: 'List all the prime numbers 100.',
    	LIST_SQUARE_NUMBERS: 'List the first 15 Square Numbers.',
    	COMP_PRIME: 'Click the composite numbers, but leave the prime numbers alone.',
    	DICE: 'For a regular dice, answer the questions about Probability and Odds.',
    	SEQUENCE: 'Determine if the sequence has a difference, ratio or neither.  Then find the 10th term and use the formulas if necessary.',
        HOME: 'Click Submit to start your next quarter quiz.',
    },
    TITLE:{
        ANG: 'Angles',
        SEQ: 'Sequences',
        PRO: 'Properties',
        PRB: 'Probability',
        PIN: 'Prime Numbers',
        PER: 'Percents',
        PTH: 'Pythagorean Theorem ',
        FRE: 'Free Pass',
        FRA: 'Fraction',
        SQU: 'Square Numbers',
        EXP: 'Exponent',
        DRU: 'Division Rules',
        DON: 'Horray!',
        HOM: 'Welcome to Quarter Quizzes!',
    }
}