
var descriptions = module.exports = {
    '1':'Euclid, sometimes called Euclid of Alexandria to distinguish him from Euclides of Megara, was a Greek mathematician, often referred to as the "father of geometry". He was active in Alexandria during the reign of Ptolemy I.',
    '2':'Sir Isaac Newton PRS was an English mathematician, astronomer, and physicist who is widely recognised as one of the most influential scientists of all time and a key figure in the scientific revolution',
    '3':'Archimedes of Syracuse was a Greek mathematician, physicist, engineer, inventor, and astronomer. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity.',
    '4':'Johann Carl Friedrich Gauss was a German mathematician who contributed significantly to many fields, including number theory, algebra, statistics, analysis, differential geometry, geodesy, geophysics, mechanics, electrostatics, astronomy, matrix theory, and optics.',
    '5':'René Descartes was a French philosopher, mathematician, and scientist. Dubbed the father of modern western philosophy, much of subsequent Western philosophy is a response to his writings, which are studied closely to this day.',
    '6':'Pierre de Fermat was a FrePierre de Fermat nch lawyer at the Parlement of Toulouse, France, and a mathematician who is given credit for early developments that led to infinitesimal calculus, including his technique of adequality.',
    '7':'Leonhard Euler was a Swiss mathematician, physicist, astronomer, logician and engineer who made important and influential discoveries in many branches of mathematics like infinitesimal calculus and graph theory while also making pioneering contributions to several branches such as topology and analytic number theory.',
    '8':'Albert Einstein was a German-born theoretical physicist. Einstein developed the theory of relativity, one of the two pillars of modern physics. Einsteins work is also known for its influence on the philosophy of science.',
    '9':'Gottfried Wilhelm Leibniz was a German polymath and philosopher who occupies a prominent place in the history of mathematics and the history of philosophy, having developed differential and integral calculus independently of Isaac Newton, his lifelong rival.',
    '10': 'David Hilbert was a German mathematician. He is recognized as one of the most influential and universal mathematicians of the 19th and early 20th centuries.',
    '11':'Blaise Pascal was a French mathematician, physicist, inventor, writer and Catholic theologian. He was a child prodigy who was educated by his father, a tax collector in Rouen.',
    '12':'Alan Mathison Turing was an English computer scientist, mathematician, logician, cryptanalyst, philosopher and theoretical biologist.',
    '13':'Srinivasa Iyengar Ramanujan FRS was an Indian mathematical genius and autodidact who lived during the British Raj.',
    '14':'Georg Friedrich Bernhard Riemann was a German mathematician who made contributions to analysis, number theory, and differential geometry. In the field of real analysis, he is mostly known for the first rigorous formulation of the integral, the Riemann integral, and his work on Fourier series.',
    '15':'John von Neumann was a Hungarian-American mathematician, physicist, inventor, computer scientist, and polymath. He made major contributions to a number of fields, including mathematics, physics, economics, computing, and statistics.',
    '16':'Claudius Ptolemy was a Greek writer, known as a mathematician, astronomer, geographer, astrologer, and poet of a single epigram in the Greek Anthology. He lived in the city of Alexandria in the Roman province of Egypt, wrote in Koine Greek, and held Roman citizenship.',
    '17':'Aryabhata I was the first of the major mathematician-astronomers from the classical age of Indian mathematics and Indian astronomy. His works include the Āryabhaṭīya and the Arya-siddhanta.',
    '18':'Georg Ferdinand Ludwig Philipp Cantor was a German mathematician. He invented set theory, which has become a fundamental theory in mathematics.',
    '19':'Marie-Sophie Germain was a French mathematician, physicist, and philosopher. Despite initial opposition from her parents and difficulties presented by society, she gained education from books in her fathers library including ones by Leonhard Euler and from correspondence with famous mathematicians such as Lagrange, Legendre, and Gauss. One of the pioneers of elasticity theory, she won the grand prize from the Paris Academy of Sciences for her essay on the subject. Her work on Fermats Last Theorem provided a foundation for mathematicians exploring the subject for hundreds of years after.',
    '20':'Augusta Ada King-Noel, Countess of Lovelace was an English mathematician and writer, chiefly known for her work on Charles Babbages proposed mechanical general-purpose computer, the Analytical Engine. She was the first to recognise that the machine had applications beyond pure calculation, and created the first algorithm intended to be carried out by such a machine. As a result, she is often regarded as the first to recognise the full potential of a "computing machine" and the first computer programmer',
    '21':'Amalie Emmy Noether was a German mathematician known for her landmark contributions to abstract algebra and theoretical physics. She was described by Pavel Alexandrov, Albert Einstein, Jean Dieudonné, Hermann Weyl, and Norbert Wiener as the most important woman in the history of mathematics.[2][3] As one of the leading mathematicians of her time, she developed the theories of rings, fields, and algebras. In physics, Noethers theorem explains the connection between symmetry and conservation laws.'
};